export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  registerVerify: "/register/verify",
  registerRecruiter: "/register/recruiter",
  registerRecruiterVerify: "/register/recruiter/verify",
  forgotPassword: "/forgot-password",
  forgotPasswordVerify: "/forgot-password/verify",
  resetPassword: "/reset-password",
  invitationAccept: "/invitations/accept",
  candidateDashboard: "/candidate/dashboard",
  candidateAssessments: "/candidate/assessments",
  candidateAttempts: "/candidate/attempts",
  recruiterDashboard: "/recruiter/dashboard",
  recruiterProblems: "/recruiter/problems",
  recruiterAssessments: "/recruiter/assessments",
  recruiterCompany: "/recruiter/company",
  recruiterBilling: "/recruiter/billing",
  adminDashboard: "/admin/dashboard",
  adminUsers: "/admin/users",
  adminAuditLogs: "/admin/audit-logs",
  adminPayments: "/admin/payments",
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];